"""Models for the governed AIOps workflow."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AIOpsRequest(BaseModel):
    """Request model for the `/api/aiops` SSE endpoint."""

    session_id: Optional[str] = Field(default="default", description="Conversation session identifier.")
    task: Optional[str] = Field(default=None, description="AIOps diagnosis task. Empty uses the default patrol task.")
    mode: Optional[str] = Field(default="default", description="`default` for patrol, `custom` for user-defined diagnosis.")

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "session-123",
                "task": "data-sync-service 出现 HighCPUUsage 告警，请排查",
                "mode": "custom",
            }
        }


class ToolPlanStep(BaseModel):
    """Structured tool execution step generated by the planner."""

    tool: str = Field(..., description="Tool name to execute.")
    args: Dict[str, Any] = Field(default_factory=dict, description="Structured tool arguments.")
    reason: str = Field(..., description="Why this tool is needed for the diagnosis.")
    evidence_type: str = Field(..., description="Evidence category collected by this step.")


class AlertInfo(BaseModel):
    """Normalized alert information used by reports."""

    alert_name: str
    severity: str
    service_name: str
    instance: str
    duration: str
    description: Optional[str] = None


class DiagnosisResponse(BaseModel):
    """Conventional JSON response model for non-stream diagnostics."""

    code: int = 200
    message: str = "success"
    data: Dict[str, Any]

    class Config:
        json_schema_extra = {
            "example": {
                "code": 200,
                "message": "success",
                "data": {
                    "status": "completed",
                    "target_alert": {
                        "alert_name": "HighCPUUsage",
                        "severity": "critical",
                        "service_name": "data-sync-service",
                    },
                    "diagnosis": {
                        "root_cause": "后台同步进程 CPU 持续冲高。",
                        "recommendations": ["排查进程热点循环", "核查最近发布和积压任务"],
                    },
                },
            }
        }
